server.port: 8080

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/tables.sql
  messages:
    basename: messages