server.port: 8080

spring.datasource:
  url: jdbc:postgresql://localhost:5432/dbcsb
  username: postgresqcsb
  password: csb123
  driver-class-name: org.postgresql.Driver

spring.jpa:
  hibernate:
    ddl-auto: create-drop
  