#Actuator infos
info.app:
  description: Mock branch office api

server.port: 8081

spring:
  application:
    name: mock-branch-office-api

#Add traceId micrometer brave
logging:
  pattern:
    level: "%5p [${spring.application.name:} - %X{traceId:-}]"

management:
  endpoints:
    #disabled not used endpoints from app context
    enabled-by-default: false
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans