CREATE TABLE IF NOT EXISTS SELLER (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    ENROLLMENT VARCHAR(12) NOT NULL UNIQUE,
    NAME VARCHAR(120) NOT NULL,
    BIRTHDAY VARCHAR(8) NULL,
    DOCUMENT_NUMBER VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    CONTRACT_TYPE VARCHAR(20) NOT NULL,
    BRANCH_OFFICE_DOCUMENT_NUMBER VARCHAR(14) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS ENROLLMENT_SEQ MAXVALUE 99999999;