BEGIN;
CREATE SEQUENCE IF NOT EXISTS ENROLLMENT_SEQ MAXVALUE 99999999;

CREATE TABLE IF NOT EXISTS BRANCH_OFFICE (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    DOCUMENT_NUMBER VARCHAR(14) NOT NULL,
    CITY VARCHAR(30),
    STATE VARCHAR(20),
    TYPE VARCHAR(30),
    ACTIVE BOOLEAN,
    CREATION_DATETIME VARCHAR(25),
    UPDATE_DATETIME VARCHAR(25) 
);

CREATE TABLE IF NOT EXISTS SELLER (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ENROLLMENT VARCHAR(12) NOT NULL UNIQUE,
    NAME VARCHAR(120) NOT NULL,
    BIRTHDAY VARCHAR(8) NULL,
    DOCUMENT_NUMBER VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    CONTRACT_TYPE VARCHAR(20) NOT NULL,
    BRANCH_OFFICE_ID INTEGER NOT NULL,
    CONSTRAINT FK_BRANCH_OFFICE_ID 
        FOREIGN KEY(BRANCH_OFFICE_ID) 
                   REFERENCES BRANCH_OFFICE(ID)
);
COMMIT;